=== sabasazad/XmlAuthoring/recipes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cookbook (description,(recipe+))>

<!ELEMENT description (#PCDATA)>

<!-- <!ELEMENT recipe (title,course,cuisine,ingredients,preparation,nutrition,preptime?,cooktime?,totaltime,comment?)> -->

<!ELEMENT recipe (title,GRAPHIC,course,cuisine,ingredients,preparation,nutrition,preptime?,cooktime?,totaltime,comment?)> 

<!ELEMENT title 	(#PCDATA)>

<!ELEMENT GRAPHIC EMPTY>

<!ATTLIST GRAPHIC

       url CDATA #REQUIRED

       width CDATA #IMPLIED

       height CDATA #IMPLIED

> 

<!ELEMENT course 	(#PCDATA)>
<!ELEMENT cuisine 	(#PCDATA)>
<!ATTLIST cuisine type (American| Mexican| Italian| French| Indian) #REQUIRED>

<!ELEMENT ingredients (ingredient+)>

<!ELEMENT ingredient (name, amount, unit)+>
<!ELEMENT name 			(#PCDATA)>
<!ELEMENT amount 		(#PCDATA)>
<!ELEMENT unit 			(#PCDATA)>

<!ELEMENT preparation (step+)>

<!ELEMENT step (#PCDATA)>

<!ELEMENT nutrition (protein, carbohydrates, fat, calories)>
<!ELEMENT protein 		(#PCDATA)>
<!ELEMENT carbohydrates 	(#PCDATA)>
<!ELEMENT fat 			(#PCDATA)>
<!ELEMENT calories 		(#PCDATA)>

<!ELEMENT preptime (#PCDATA)>
<!ELEMENT cooktime (#PCDATA)>
<!ELEMENT totaltime (#PCDATA)>

<!ELEMENT comment (#PCDATA)>

=== sabasazad/XmlAuthoring/Recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2021 rel. 3 (x64) (http://www.altova.com)-->
<?xml-stylesheet href="recipes.xsl" type="text/xsl"?>
<!DOCTYPE cookbook SYSTEM "recipes.dtd">
<cookbook>
  <description>Some recipes for the cookbook.</description>
  <recipe>
    <title>White Pasta with Beef</title>
    <GRAPHIC url="white-pasta-with-beef.jpg"/>
    <course>Main</course>
    <cuisine type = "American"></cuisine>
    <ingredients>
      <ingredient>
        <name>ground beef</name>
        <amount>1/2</amount>
        <unit>pound</unit>
      </ingredient>
      <ingredient>
        <name>penne pasta</name>
        <amount>2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>vegetable broth</name>
        <amount>2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>onion</name>
        <amount>1/2</amount>
        <unit></unit>
      </ingredient>
      <ingredient>
        <name>water</name>
        <amount>2 and 1/2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>basil (chopped)</name>
        <amount>1/2</amount>
        <unit>cup</unit>
      </ingredient>
      <ingredient>
        <name>garlic clove</name>
        <amount>1</amount>
        <unit></unit>
      </ingredient>
      <ingredient>
        <name>ground black pepper</name>
        <amount>1/8</amount>
        <unit>teaspoon</unit>
      </ingredient>
      <ingredient>
        <name>cooking spray</name>
        <amount></amount>
        <unit></unit>
      </ingredient>
      <ingredient>
        <name>cream cheese</name>
        <amount>4</amount>
        <unit>ounce</unit>
      </ingredient>
      <ingredient>
        <name>lemon</name>
        <amount>1</amount>
        <unit></unit>
      </ingredient>
      <ingredient>
        <name>grated parmesan cheese</name>
        <amount>1/2</amount>
        <unit>cup</unit>
      </ingredient>
    </ingredients>
    <preparation>
      <step>Add uncooked pasta, water, and broth to a large stockpot. Slice onion and add to pot along with basil, minced garlic,      salt, and pepper. Cover and cook on medium-high, bringing to a boil. Remove cover and cook for 8-10 minutes or until liquid has completely absorbed, stirring occasionally.</step>
      <step>Meanwhile, spray a skillet with cooking spray and heat over medium. Add beef and cook until browned, stirring to 			 	crumble.	</step>
      <step>Add beef to cooked pasta. Stir in cream cheese, 2-3 tablespoons of fresh lemon juice, zest of lemon, and Parmesan 	  cheese.		</step>
      <step>Serve with orange wedges on the side.</step>
    </preparation>
    <nutrition>
      <protein>28g</protein>
      <carbohydrates>63g</carbohydrates>
      <fat>11g</fat>
      <calories>458</calories>
    </nutrition>
    <preptime>15mins</preptime>
    <cooktime>20mins</cooktime>
    <totaltime>35mins</totaltime>
    <comment>A healthy and yummy recipe for dinner for kids, who are picky eaters.</comment>
  </recipe>
</cookbook>
